#!/usr/bin/env python3

print("=" * 80)
print("Summary: Polynomial-Time Computable Properties")
print("=" * 80)

print("\n## O(n²) Properties (Pair Counting):")
print("-" * 80)
print()
print("Property 16: Number of commuting pairs (ab = ba)")
print("  Total time: 289 ms")
print("  Average: 0.93 ms per group")
print("  Interpretation: Measures 'how abelian' the group is")
print("  Abelian groups: n² pairs (all pairs commute)")
print()
print("Property 22: Number of pairs where a²b = b²a (NEW!)")
print("  Total time: 779 ms")
print("  Average: 2.50 ms per group")
print("  Interpretation: Measures compatibility of squares")
print("  288/312 groups have exactly n pairs (minimal)")
print("  24 groups have excess pairs (interesting structure)")
print("  Highest: SmallGroup(48,50) with 528 pairs (22.9% of n²)")
print()
print("Speed ratio: Property 22 is 2.7x slower than Property 16")
print()

print("\n## O(n³) Properties (Triple Counting):")
print("-" * 80)
print()
print("Property 17: Number of triples where abc = cab")
print("  Total time: 22,549 ms")
print("  Average: 72.3 ms per group")
print("  Interpretation: Measures 'partial commutativity' of operations")
print("  Abelian groups: n³ triples (all triples satisfy this)")
print("  Non-abelian groups: significantly fewer")
print()
print("Speed comparison:")
print("  Property 17 is 78x slower than Property 16")
print("  Property 17 is 29x slower than Property 22")
print()

print("\n## Timing Analysis:")
print("-" * 80)
print()
print("Operation          | Complexity | Total Time | Avg per Group | Ratio to ab=ba")
print("-------------------|------------|------------|---------------|---------------")
print("ab = ba (P16)      | O(n²)      |    289 ms  |   0.93 ms     |     1.0x")
print("a²b = b²a (P22)    | O(n²)      |    779 ms  |   2.50 ms     |     2.7x")
print("abc = cab (P17)    | O(n³)      | 22,549 ms  |  72.28 ms     |    78.0x")
print()

print("\n## Mathematical Insights:")
print("-" * 80)
print()
print("For ab = ba:")
print("  - Abelian groups: always n² pairs")
print("  - Measures the size of center squared (roughly)")
print()
print("For a²b = b²a:")
print("  - Even abelian groups can have just n pairs!")
print("  - In abelian groups: a²b = b²a iff a² = b²")
print("  - Forms equivalence classes based on the square map")
print("  - Some non-abelian groups have many such pairs")
print()
print("For abc = cab:")
print("  - Abelian groups: always n³ triples")
print("  - Measures how close to abelian the group is")
print("  - High variance: up to 12x difference within same order")
print()

print("\n## Recommendation:")
print("-" * 80)
print("✓ O(n²) properties are VERY fast (<1 second total)")
print("✓ O(n³) properties are acceptable (<25 seconds total)")
print("✓ Both can be computed for all groups of order ≤ 60 efficiently")
print()
print("Property a²b = b²a is a good discriminator:")
print("  - Fast to compute (779 ms)")
print("  - Shows interesting structural differences")
print("  - Could help distinguish groups")
print()

print("=" * 80)
